Feat/724 ios asset catalog
pluralsight/tva pull request #918
Opened 2022-12-15 18:27 UTC by caseybaggz

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
closes #724 

## What is the new behavior?
- Adds support for iOS AssetCatalog in mobile config
- Adds iOS AssetCatalog in `build-mobile`

## Other information

2022-12-15 18:32 UTC, caseybaggz commented
@kaydenthomson can you validate the Assets created for colors? I have no idea if it's how the team prefers, but we have 6 diff sentiment groups from our theme (default, action, info, success, warning, danger) and each of the tokens within those have different theme versions (light, dark, etc.).

2022-12-15 18:42 UTC, Rykus0 approved these changes

2022-12-15 20:06 UTC, kaydenthomson requested changes

2022-12-15 20:06 UTC, kaydenthomson commented on packages/design-tokens/utils/actions/iOS.cjs
> +    const colorsetPath = `${assetPath}/${token.name}.colorset`
The current output is providing two files. 
`psActionBackgroundActiveFlowDark.colorset` 
`psActionBackgroundActiveFlowLight.colorset`

In order for the system to properly identify light/dark mode. We need this condensed down to a single file
`psActionBackgroundActiveFlow.colorset` with 3 colors in the array [universal, dark, light] universal can just be dark without the `appearances` attribute. (see comment below)


Additionally, it would be awesome to organize these a bit more if possible. 
Having some additional folder structure similar to what you have laid out [here](https://design.pluralsight.com/docs/development/tokens/colors).  
- Default
- Action
- Info
- Success
- Warning
- Danger

(Note: Text case doesn't matter.)

I'm not sure if these folders are available to you here. But if there are you would just prefix your existing line here:
```
const colorsetPath = `${folderName}/${assetPath}/${token.name}.colorset`
```

If you're not able to add to the folder structure, no worries. It's just a developer experience improvement.

2022-12-16 22:51 UTC, caseybaggz commented on packages/design-tokens/utils/actions/iOS.cjs
> +    }
Done.

2022-12-16 22:51 UTC, caseybaggz commented on packages/design-tokens/utils/actions/iOS.cjs
> +    const colorsetPath = `${assetPath}/${token.name}.colorset`
Done.

2022-12-19 13:55 UTC, Rykus0 submitted a review, later dismissed

2023-01-04 16:48 UTC, kaydenthomson approved these changes

2023-01-04 16:50 UTC, merged